language: python
python:
  - "2.7"
before_script: 
  - pip install nose
  - cp errbot/config-template.py config.py
  - pip freeze

install: pip install -r requirements.txt
script: nosetests -v tests/ 
